---
- name: Include distribution dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install Bareos client packages (CentOS or AlmaLinux)
  yum:
    name: "bareos-client-{{ bareos_version }}"
    state: installed
  when: >
    ansible_distribution == "CentOS" or
    ansible_distribution == "AlmaLinux" 
  tags: [bareos-client]

- name: Install Bareos client packages (Virtuozzo 7)
  yum:
    name: "bareos-client-{{ bareos_version }}"
    state: installed
  when: ansible_distribution == "Virtuozzo"
  tags: [bareos-client]

- name: Install Bareos client packages (Debian or Ubuntu)
  apt:
    name: "bareos-client"
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: [bareos-client]

- name: Check if /usr/bin/mysql is present
  stat:
    path: "/usr/bin/mysql"
  register: mysql

- name: Check if /usr/sbin/mysql is present
  stat:
    path: "/usr/bin/mysql"
  register: sbin_mysql

- name: Install bareos-filedaemon-python-plugin (CentOS, Bareos=19)
  yum:
    name: "bareos-filedaemon-python-plugin-{{ bareos_version }}"
    state: installed
  when: >
    ansible_distribution == "CentOS" and 
    (mysql.stat.exists or sbin_mysql.stat.exists) and
    "19." in bareos_version

- name: Install bareos-filedaemon-python-plugin (CentOS, Bareos >= 20)
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - bareos-filedaemon-python2-plugin
  when: >
    (ansible_distribution == "CentOS" and 
    (mysql.stat.exists or sbin_mysql.stat.exists)) and
    "19." not in bareos_version

- name: Install bareos-filedaemon-python-plugin (Debian or Ubuntu, Bareos=19)
  apt:
    name: "bareos-filedaemon-python-plugin"
    state: present
    update_cache: yes
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists)) and
    "19." in bareos_version

- name: Install bareos-filedaemon-python-plugin (Debian or Ubuntu, Bareos >= 20)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - bareos-filedaemon-python2-plugin
  when: >
    ((ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists))) and
    "19." not in bareos_version

- name: Enable and start the services
  service:
    name: bareos-fd
    enabled: yes
    state: started
  tags: [bareos-client]

- name: Ensure MySQL plugin directory exists
  file:
    path: "{{ bareos_plugins_location }}"
    state: directory
    mode: 0755

- name: Upload MySQL plugins
  copy:
    src: "{{ item }}"
    dest: "{{ bareos_plugins_location }}"
    mode: 0755
    owner: root
    group: root
  loop:
    - BareosFdMySQLclass.py
    - bareos-fd-mysql.py
