---

- name: Install Bareos client packages (CentOS)
  yum:
    name: "bareos-client-{{ bareos_version }}"
    state: installed
  when: ansible_distribution == "CentOS"
  tags: [bareos-client]

- name: Install Bareos client packages (Virtuozzo 7)
  yum:
    name: "bareos-client-{{ bareos_version }}"
    state: installed
  when: ansible_distribution == "Virtuozzo"
  tags: [bareos-client]

- name: Install Bareos client packages (Debian or Ubuntu)
  apt:
    name: "bareos-client-{{ bareos_version }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: [bareos-client]

- name: Check if /usr/bin/mysql is present
  stat:
    path: "/usr/bin/mysql"
  register: mysql

- name: Check if /usr/sbin/mysql is present
  stat:
    path: "/usr/bin/mysql"
  register: sbin_mysql

- name: Install bareos-filedaemon-python-plugin (CentOS, Bareos=19)
  yum:
    name: "bareos-filedaemon-python-plugin-{{ bareos_version }}"
    state: installed
  when: >
    ansible_distribution == "CentOS" and 
    (mysql.stat.exists or sbin_mysql.stat.exists) and
    "19." in bareos_version

- name: Install bareos-filedaemon-python-plugin (CentOS, Bareos >= 20)
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - bareos-filedaemon-python2-plugin
  when: >
    ansible_distribution == "CentOS" and 
    (mysql.stat.exists or sbin_mysql.stat.exists) and not
    "19." in bareos_version

- name: Install bareos-filedaemon-python-plugin (Debian or Ubuntu, Bareos=19)
  apt:
    name: "bareos-filedaemon-python-plugin-{{ bareos_version }}"
    state: present
    update_cache: yes
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists)) and
    "19." in bareos_version

- name: Install bareos-filedaemon-python-plugin (Debian or Ubuntu, Bareos >= 20)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - bareos-filedaemon-python2-plugin
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists)) and not
    "19." in bareos_version

- name: Enable and start the services
  service:
    name: bareos-fd
    enabled: yes
    state: started
  tags: [bareos-client]

- name: Download MySQL plugin (CentOS, Bareos >= 20)
  get_url:
    url: "{{ item }}"
    dest: "{{ bareos_plugins_location_centos }}"
    mode: 0755
  loop:
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/BareosFdMySQLclass.py"
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/bareos-fd-mysql.py"
  when: >
    ansible_distribution == "CentOS" and 
    (mysql.stat.exists or sbin_mysql.stat.exists) and not
    "19." in bareos_version
  tags: [bareos-client]

- name: Upload MySQL plugin (CentOS, Bareos=19)
  copy:
    src: "{{ item }}"
    dest: "{{ bareos_plugins_location_centos }}"
    mode: 0755
  loop:
    - BareosFdMySQLclass.py
    - bareos-fd-mysql.py
  when: >
    ansible_distribution == "CentOS" and 
    (mysql.stat.exists or sbin_mysql.stat.exists) and
    "19." in bareos_version

- name: Download MySQL plugin (Debian and Ubuntu, Bareos >= 20)
  get_url:
    url: "{{ item }}"
    dest: "{{ bareos_plugins_location_deb }}"
    mode: 0755
  loop:
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/BareosFdMySQLclass.py"
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/bareos-fd-mysql.py"
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists)) and not
    "19." in bareos_version
  tags: [bareos-client]

- name: Upload MySQL plugin (Debian and Ubuntu, Bareos=19)
  copy:
    src: "{{ item }}"
    dest: "{{ bareos_plugins_location_centos }}"
  loop:
    - BareosFdMySQLclass.py
    - bareos-fd-mysql.py
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists)) and
    "19." in bareos_version
