---

- name: Configure director in {{ bareos_root_dir }}/bareos-fd.d/director/bareos-dir.conf (Client)
  template:
    src: "bareos-dir.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-fd.d/director/bareos-dir.conf"
  notify: "Restart bareos-fd"
  tags:
    - bareos-client
    - bareos-client-configure

- name: Configure filedaemon in {{ bareos_root_dir }}/bareos-fd.d/client/myself.conf
  template:
    src: "myself.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-fd.d/client/myself.conf"
  notify: "Restart bareos-fd"
  tags:
    - bareos-client
    - bareos-client-configure
