---

- name: Install Bareos client packages (CentOS)
  yum:
    name: bareos-client
    state: installed
  when: ansible_distribution == "CentOS"
  tags: [bareos-client]

- name: Install Bareos client packages (Debian or Ubuntu)
  apt:
    name: bareos-client
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: [bareos-client]

- name: Check if /usr/bin/mysql is present
  stat:
    path: "/usr/bin/mysql"
  register: mysql

- name: Check if /usr/sbin/mysql is present
  stat:
    path: "/usr/bin/mysql"
  register: sbin_mysql

- name: Install bareos-filedaemon-python-plugin (CentOS)
  yum:
    name: bareos-filedaemon-python-plugin
    state: installed
  when: ansible_distribution == "CentOS" and (mysql.stat.exists or sbin_mysql.stat.exists)

- name: Install bareos-filedaemon-python-plugin (Debian or Ubuntu)
  apt:
    name: bareos-filedaemon-python-plugin
    state: present
    update_cache: yes
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists))

- name: Enable and start the services
  service:
    name: bareos-fd
    enabled: yes
    state: started
  tags: [bareos-client]

- name: Download MySQL plugin (CentOS)
  get_url:
    url: "{{ item }}"
    dest: "{{ bareos_plugins_location_centos }}"
    mode: 0755
  loop:
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/BareosFdMySQLclass.py"
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/bareos-fd-mysql.py"
  when: ansible_distribution == "CentOS" and (mysql.stat.exists or sbin_mysql.stat.exists)
  tags: [bareos-client]

- name: Download MySQL plugin (Debian and Ubuntu)
  get_url:
    url: "{{ item }}"
    dest: "{{ bareos_plugins_location_deb }}"
    mode: 0755
  loop:
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/BareosFdMySQLclass.py"
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/bareos-fd-mysql.py"
  when: >
    (ansible_distribution == "Debian" and (mysql.stat.exists or sbin_mysql.stat.exists)) or 
    (ansible_distribution == "Ubuntu" and (mysql.stat.exists or sbin_mysql.stat.exists))
  tags: [bareos-client]
